FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git libexpat-dev lua5.3-dev ragel

RUN git clone https://github.com/vovkos/doxyrest_b --recursive
RUN rm -rf /doxyrest_b/doxyrest
COPY . /doxyrest_b/doxyrest
WORKDIR /doxyrest_b/build
RUN cmake ..
RUN make -j8

